export const TEMPLATES = [
  {
    id: 1,
    name: 'Teal Classic',
    file: '/cert-templates/template_01.png',
    textColor: '#005f6e',
    barColor: '#00bcd4',
    nameZone: { top: 440, bottom: 542, centerX: 1024 },
  },
  {
    id: 2,
    name: 'Dark Teal',
    file: '/cert-templates/template_02.png',
    textColor: '#ffffff',
    barColor: '#0097a7',
    nameZone: { top: 440, bottom: 542, centerX: 1024 },
  },
  {
    id: 3,
    name: 'Ocean Blue',
    file: '/cert-templates/template_03.png',
    textColor: '#005f6e',
    barColor: '#00bcd4',
    nameZone: { top: 440, bottom: 542, centerX: 1024 },
  },
  {
    id: 4,
    name: 'Modern Teal',
    file: '/cert-templates/template_04.png',
    textColor: '#0097a7',
    barColor: '#ffffff',
    nameZone: { top: 440, bottom: 542, centerX: 1024 },
  },
  {
    id: 5,
    name: 'Elegant White',
    file: '/cert-templates/template_05.png',
    textColor: '#005f6e',
    barColor: '#0097a7',
    nameZone: { top: 440, bottom: 542, centerX: 1024 },
  },
  {
    id: 6,
    name: 'SLS Signature',
    file: '/cert-templates/template_06.png',
    textColor: '#ffffff',
    barColor: '#005f6e',
    nameZone: { top: 440, bottom: 542, centerX: 1024 },
  },
];
